TRAINING_DAYS = [
    {
        "id": "day-1",
        "name": "Dia 1",
        "muscle_groups": ["Pecho", "Biceps"],
        "default_active_ids": [
            "chest-bench-press",
            "chest-incline-dumbbell-press",
            "chest-cable-fly",
            "biceps-barbell-curl",
            "biceps-hammer-curl",
            "biceps-preacher-curl",
        ],
    },
    {
        "id": "day-2",
        "name": "Dia 2",
        "muscle_groups": ["Espalda", "Triceps"],
        "default_active_ids": [
            "back-lat-pulldown",
            "back-single-arm-row",
            "back-tbar-row",
            "triceps-close-grip-bench",
            "triceps-pushdown",
            "triceps-overhead-extension",
        ],
    },
    {
        "id": "day-3",
        "name": "Dia 3",
        "muscle_groups": ["Hombros"],
        "default_active_ids": [
            "shoulders-lateral-raise",
            "shoulders-front-raise",
            "shoulders-arnold-press",
            "shoulders-rear-delt-fly",
            "shoulders-overhead-press",
            "shoulders-dumbbell-press",
        ],
    },
    {
        "id": "day-4",
        "name": "Dia 4",
        "muscle_groups": ["Piernas"],
        "default_active_ids": [
            "legs-back-squat",
            "legs-goblet-squat",
            "legs-leg-extension",
            "legs-romanian-deadlift",
            "legs-box-step-up",
            "legs-standing-calf-raise",
        ],
    },
]


EXERCISE_LIBRARY = [
    {"id": "back-lat-pulldown", "name": "Tirones en polea alta agarre amplio", "muscle_group": "Espalda"},
    {"id": "back-single-arm-row", "name": "Remo a 1 mano", "muscle_group": "Espalda"},
    {"id": "back-tbar-row", "name": "Remo potro Landmine", "muscle_group": "Espalda"},
    {"id": "back-seated-row", "name": "Remo bajo", "muscle_group": "Espalda"},
    {"id": "back-single-leg-row", "name": "Remo bajo unipodal", "muscle_group": "Espalda"},
    {"id": "back-supinated-pulldown", "name": "Tirones polea alta con agarre supino", "muscle_group": "Espalda"},
    {"id": "back-barbell-row", "name": "Remo con barra", "muscle_group": "Espalda"},
    {"id": "back-triangle-pulldown", "name": "Tirones polea alta con triangulo", "muscle_group": "Espalda"},
    {"id": "back-pull-up", "name": "Dominadas", "muscle_group": "Espalda"},
    {"id": "back-behind-neck-pulldown", "name": "Tirones polea alta tras nuca", "muscle_group": "Espalda"},
    {"id": "back-straight-arm-pulldown", "name": "Pullover en polea alta", "muscle_group": "Espalda"},
    {"id": "biceps-barbell-curl", "name": "Curl barra", "muscle_group": "Biceps"},
    {"id": "biceps-incline-curl", "name": "Curl supinado banco inclinado", "muscle_group": "Biceps"},
    {"id": "biceps-hammer-curl", "name": "Curl martillo", "muscle_group": "Biceps"},
    {"id": "biceps-preacher-curl", "name": "Banco Scott", "muscle_group": "Biceps"},
    {"id": "biceps-concentration-curl", "name": "Concentrado con mancuerna", "muscle_group": "Biceps"},
    {"id": "biceps-spider-curl", "name": "Spiderman con barra o mancuerna", "muscle_group": "Biceps"},
    {"id": "triceps-close-grip-bench", "name": "Press barra angosta", "muscle_group": "Triceps"},
    {"id": "triceps-pushdown", "name": "Polea alta", "muscle_group": "Triceps"},
    {"id": "triceps-overhead-extension", "name": "Copa", "muscle_group": "Triceps"},
    {"id": "triceps-skullcrusher", "name": "Frances con barra W", "muscle_group": "Triceps"},
    {"id": "triceps-dumbbell-french-press", "name": "Frances con mancuernas", "muscle_group": "Triceps"},
    {"id": "triceps-rope-pushdown", "name": "Polea alta con soga", "muscle_group": "Triceps"},
    {"id": "shoulders-lateral-raise", "name": "Vuelo lateral", "muscle_group": "Hombros"},
    {"id": "shoulders-front-raise", "name": "Vuelo frontal", "muscle_group": "Hombros"},
    {"id": "shoulders-arnold-press", "name": "Press Arnold", "muscle_group": "Hombros"},
    {"id": "shoulders-rear-delt-fly", "name": "Posteriores con mancuernas", "muscle_group": "Hombros"},
    {"id": "shoulders-overhead-press", "name": "Press militar con barra", "muscle_group": "Hombros"},
    {"id": "shoulders-dumbbell-press", "name": "Press militar con mancuerna", "muscle_group": "Hombros"},
    {"id": "shoulders-upright-row", "name": "Remo al menton agarre amplio con W", "muscle_group": "Hombros"},
    {"id": "shoulders-barbell-shrug", "name": "Encogimientos con barra", "muscle_group": "Hombros"},
    {"id": "shoulders-face-pull", "name": "Face pull", "muscle_group": "Hombros"},
    {"id": "legs-back-squat", "name": "Sentadilla libre", "muscle_group": "Piernas"},
    {"id": "legs-goblet-squat", "name": "Sentadilla goblet", "muscle_group": "Piernas"},
    {"id": "legs-leg-extension", "name": "Extensiones", "muscle_group": "Piernas"},
    {"id": "legs-romanian-deadlift", "name": "Peso muerto rumano", "muscle_group": "Piernas"},
    {"id": "legs-box-step-up", "name": "Subidas al cajon", "muscle_group": "Piernas"},
    {"id": "legs-standing-calf-raise", "name": "Gemelos", "muscle_group": "Piernas"},
    {"id": "legs-bulgarian-split-squat", "name": "Bulgaras", "muscle_group": "Piernas"},
    {"id": "legs-walking-lunge", "name": "Estocadas", "muscle_group": "Piernas"},
    {"id": "legs-leg-press", "name": "Prensa a 45 grados", "muscle_group": "Piernas"},
    {"id": "legs-conventional-deadlift", "name": "Peso muerto convencional", "muscle_group": "Piernas"},
    {"id": "legs-leg-curl", "name": "Izquiotibiales en banco", "muscle_group": "Piernas"},
    {"id": "legs-sissy-squat", "name": "Sissy Squat", "muscle_group": "Piernas"},
    {"id": "legs-sumo-deadlift", "name": "Sumo", "muscle_group": "Piernas"},
    {"id": "chest-bench-press", "name": "Press en banco plano con barra", "muscle_group": "Pecho"},
    {"id": "chest-incline-dumbbell-press", "name": "Press en banco inclinado con barra", "muscle_group": "Pecho"},
    {"id": "chest-cable-fly", "name": "Apertura inclinadas con mancuernas", "muscle_group": "Pecho"},
    {"id": "chest-front-raise-45", "name": "Elevaciones en banco 45 grados con mancuernas", "muscle_group": "Pecho"},
    {"id": "chest-pec-deck", "name": "Peck Deck", "muscle_group": "Pecho"},
    {"id": "chest-machine-press", "name": "Press banco plano con mancuernas", "muscle_group": "Pecho"},
    {"id": "chest-push-up", "name": "Push ups", "muscle_group": "Pecho"},
]
