TRAINING_DAYS = [
    {
        "id": "day-1",
        "name": "Día 1",
        "muscle_groups": ["Pecho", "Bíceps"],
        "default_active_ids": [
            "chest-bench-press",
            "chest-incline-dumbbell-press",
            "chest-cable-fly",
            "biceps-barbell-curl",
            "biceps-hammer-curl",
            "biceps-preacher-curl",
        ],
    },
    {
        "id": "day-2",
        "name": "Día 2",
        "muscle_groups": ["Espalda", "Tríceps"],
        "default_active_ids": [
            "back-lat-pulldown",
            "back-seated-row",
            "back-barbell-row",
            "triceps-pushdown",
            "triceps-overhead-extension",
            "triceps-close-grip-bench",
        ],
    },
    {
        "id": "day-3",
        "name": "Día 3",
        "muscle_groups": ["Hombros"],
        "default_active_ids": [
            "shoulders-overhead-press",
            "shoulders-lateral-raise",
            "shoulders-rear-delt-fly",
            "shoulders-arnold-press",
            "shoulders-upright-row",
            "shoulders-face-pull",
        ],
    },
    {
        "id": "day-4",
        "name": "Día 4",
        "muscle_groups": ["Piernas"],
        "default_active_ids": [
            "legs-back-squat",
            "legs-leg-press",
            "legs-romanian-deadlift",
            "legs-leg-extension",
            "legs-leg-curl",
            "legs-standing-calf-raise",
        ],
    },
]


EXERCISE_LIBRARY = [
    {"id": "chest-bench-press", "name": "Press de banca plano", "muscle_group": "Pecho"},
    {"id": "chest-incline-dumbbell-press", "name": "Press inclinado con mancuernas", "muscle_group": "Pecho"},
    {"id": "chest-decline-press", "name": "Press declinado", "muscle_group": "Pecho"},
    {"id": "chest-cable-fly", "name": "Aperturas en polea", "muscle_group": "Pecho"},
    {"id": "chest-pec-deck", "name": "Pec deck", "muscle_group": "Pecho"},
    {"id": "chest-push-up", "name": "Flexiones", "muscle_group": "Pecho"},
    {"id": "chest-dumbbell-fly", "name": "Aperturas con mancuernas", "muscle_group": "Pecho"},
    {"id": "chest-machine-press", "name": "Press en máquina", "muscle_group": "Pecho"},
    {"id": "chest-chest-dips", "name": "Fondos para pecho", "muscle_group": "Pecho"},
    {"id": "chest-low-cable-fly", "name": "Aperturas bajas en polea", "muscle_group": "Pecho"},
    {"id": "biceps-barbell-curl", "name": "Curl con barra", "muscle_group": "Bíceps"},
    {"id": "biceps-hammer-curl", "name": "Curl martillo", "muscle_group": "Bíceps"},
    {"id": "biceps-preacher-curl", "name": "Curl predicador", "muscle_group": "Bíceps"},
    {"id": "biceps-incline-curl", "name": "Curl inclinado", "muscle_group": "Bíceps"},
    {"id": "biceps-cable-curl", "name": "Curl en polea", "muscle_group": "Bíceps"},
    {"id": "biceps-concentration-curl", "name": "Curl concentrado", "muscle_group": "Bíceps"},
    {"id": "biceps-ez-bar-curl", "name": "Curl con barra EZ", "muscle_group": "Bíceps"},
    {"id": "biceps-spider-curl", "name": "Spider curl", "muscle_group": "Bíceps"},
    {"id": "biceps-reverse-curl", "name": "Curl invertido", "muscle_group": "Bíceps"},
    {"id": "biceps-machine-curl", "name": "Curl en máquina", "muscle_group": "Bíceps"},
    {"id": "back-lat-pulldown", "name": "Jalón al pecho", "muscle_group": "Espalda"},
    {"id": "back-seated-row", "name": "Remo sentado", "muscle_group": "Espalda"},
    {"id": "back-barbell-row", "name": "Remo con barra", "muscle_group": "Espalda"},
    {"id": "back-tbar-row", "name": "Remo T-Bar", "muscle_group": "Espalda"},
    {"id": "back-single-arm-row", "name": "Remo a un brazo", "muscle_group": "Espalda"},
    {"id": "back-pull-up", "name": "Dominadas", "muscle_group": "Espalda"},
    {"id": "back-straight-arm-pulldown", "name": "Pullover en polea", "muscle_group": "Espalda"},
    {"id": "back-deadlift", "name": "Peso muerto", "muscle_group": "Espalda"},
    {"id": "back-machine-row", "name": "Remo en máquina", "muscle_group": "Espalda"},
    {"id": "back-chest-supported-row", "name": "Remo pecho apoyado", "muscle_group": "Espalda"},
    {"id": "triceps-pushdown", "name": "Extensión en polea", "muscle_group": "Tríceps"},
    {"id": "triceps-overhead-extension", "name": "Extensión por encima de la cabeza", "muscle_group": "Tríceps"},
    {"id": "triceps-close-grip-bench", "name": "Press cerrado", "muscle_group": "Tríceps"},
    {"id": "triceps-bench-dips", "name": "Fondos en banco", "muscle_group": "Tríceps"},
    {"id": "triceps-skullcrusher", "name": "Rompecráneos", "muscle_group": "Tríceps"},
    {"id": "triceps-rope-pushdown", "name": "Polea con soga", "muscle_group": "Tríceps"},
    {"id": "triceps-kickback", "name": "Patada de tríceps", "muscle_group": "Tríceps"},
    {"id": "triceps-machine-dip", "name": "Fondos en máquina", "muscle_group": "Tríceps"},
    {"id": "triceps-single-arm-pushdown", "name": "Polea unilateral", "muscle_group": "Tríceps"},
    {"id": "triceps-diamond-pushup", "name": "Flexiones diamante", "muscle_group": "Tríceps"},
    {"id": "shoulders-overhead-press", "name": "Press militar", "muscle_group": "Hombros"},
    {"id": "shoulders-lateral-raise", "name": "Elevaciones laterales", "muscle_group": "Hombros"},
    {"id": "shoulders-front-raise", "name": "Elevaciones frontales", "muscle_group": "Hombros"},
    {"id": "shoulders-rear-delt-fly", "name": "Pájaros", "muscle_group": "Hombros"},
    {"id": "shoulders-arnold-press", "name": "Press Arnold", "muscle_group": "Hombros"},
    {"id": "shoulders-upright-row", "name": "Remo al mentón", "muscle_group": "Hombros"},
    {"id": "shoulders-face-pull", "name": "Face pull", "muscle_group": "Hombros"},
    {"id": "shoulders-machine-press", "name": "Press en máquina", "muscle_group": "Hombros"},
    {"id": "shoulders-cable-lateral-raise", "name": "Laterales en polea", "muscle_group": "Hombros"},
    {"id": "shoulders-reverse-pec-deck", "name": "Reverse pec deck", "muscle_group": "Hombros"},
    {"id": "legs-back-squat", "name": "Sentadilla trasera", "muscle_group": "Piernas"},
    {"id": "legs-front-squat", "name": "Sentadilla frontal", "muscle_group": "Piernas"},
    {"id": "legs-leg-press", "name": "Prensa", "muscle_group": "Piernas"},
    {"id": "legs-romanian-deadlift", "name": "Peso muerto rumano", "muscle_group": "Piernas"},
    {"id": "legs-leg-extension", "name": "Extensiones de cuádriceps", "muscle_group": "Piernas"},
    {"id": "legs-leg-curl", "name": "Curl femoral", "muscle_group": "Piernas"},
    {"id": "legs-bulgarian-split-squat", "name": "Sentadilla búlgara", "muscle_group": "Piernas"},
    {"id": "legs-hip-thrust", "name": "Hip thrust", "muscle_group": "Piernas"},
    {"id": "legs-standing-calf-raise", "name": "Elevación de gemelos de pie", "muscle_group": "Piernas"},
    {"id": "legs-seated-calf-raise", "name": "Elevación de gemelos sentado", "muscle_group": "Piernas"},
]
