"""users, attendance, audit fields, unique payment period

Revision ID: 5675bcbe61db
Revises: 250d5083b4e6
Create Date: 2025-10-06 18:42:54.347377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5675bcbe61db'
down_revision: Union[str, Sequence[str], None] = '250d5083b4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'coach', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('attendances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('checkin_at', sa.DateTime(), nullable=False),
    sa.Column('coach_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendances_client_id'), 'attendances', ['client_id'], unique=False)
    op.add_column('clients', sa.Column('created_by_user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    op.add_column('payments', sa.Column('created_by_user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'created_by_user_id')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'created_by_user_id')
    op.drop_index(op.f('ix_attendances_client_id'), table_name='attendances')
    op.drop_table('attendances')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
