"""add method_channel to payments

Revision ID: 6f2f737d5dba
Revises: a0f346917752
Create Date: 2025-10-27 11:35:17.475795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2f737d5dba'
down_revision: Union[str, Sequence[str], None] = 'a0f346917752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('method_channel', sa.String(), nullable=True))
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_period'), table_name='payments')
    op.create_index('ix_payments_method_channel', 'payments', ['method_channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_method_channel', table_name='payments')
    op.create_index(op.f('ix_payments_period'), 'payments', ['period_year', 'period_month'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('payments', 'method_channel')
    # ### end Alembic commands ###
